function cardsForStage(cards, stage) {
  return cards.filter((card) => card.stage === stage);
}

export function OutreachKanban({ kanban, onMoveCard, readOnly = false }) {
  return (
    <section className="atlas-panel">
      <div className="panel-head">
        <h2>Outreach Kanban</h2>
        <p>
          Execution pipeline generated by Next Best Action agent
          {readOnly ? " (read-only for your role)" : ""}
        </p>
      </div>

      <div className="kanban-grid">
        {kanban.columns.map((column) => (
          <div key={column.id} className="kanban-column">
            <header>
              <h3>{column.title}</h3>
              <span>{cardsForStage(kanban.cards, column.id).length}</span>
            </header>

            <div className="kanban-cards">
              {cardsForStage(kanban.cards, column.id).map((card) => (
                <article key={card.id} className="kanban-card">
                  <p className="kanban-account">{card.accountName}</p>
                  <p>{card.task}</p>
                  <footer>
                    <span>{card.owner}</span>
                    <strong>{card.score}</strong>
                  </footer>
                  <small>
                    Due {card.dueDate ? new Date(card.dueDate).toLocaleDateString() : "TBD"}
                  </small>

                  <div className="kanban-actions">
                    <button type="button" onClick={() => onMoveCard(card.id, "left")} disabled={readOnly}>
                      Move Left
                    </button>
                    <button type="button" onClick={() => onMoveCard(card.id, "right")} disabled={readOnly}>
                      Move Right
                    </button>
                  </div>
                </article>
              ))}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
