import { useState } from "react";

export function StrategyBrief({ brief }) {
  const [copied, setCopied] = useState(false);

  const copyBrief = async () => {
    try {
      await navigator.clipboard.writeText(brief.markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch {
      setCopied(false);
    }
  };

  return (
    <section className="atlas-panel">
      <div className="panel-head">
        <h2>Daily Strategy Brief Generator</h2>
        <p>Autogenerated summary for standup and planning</p>
      </div>

      <article className="brief-card">
        <div className="brief-headline-row">
          <h3>{brief.headline}</h3>
          <button type="button" onClick={copyBrief}>
            {copied ? "Copied" : "Copy Brief"}
          </button>
        </div>

        <div className="brief-grid">
          <div>
            <h4>Top Actions</h4>
            <ol>
              {brief.actions.map((action) => (
                <li key={`${action.accountId}-${action.action}`}>{action.action}</li>
              ))}
            </ol>
          </div>

          <div>
            <h4>Priority Themes</h4>
            <ul>
              {brief.themes.map((theme) => (
                <li key={theme.tag}>
                  {theme.tag} ({theme.count})
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4>Watchlist</h4>
            <ul>
              {brief.riskAccounts.length ? (
                brief.riskAccounts.map((name) => <li key={name}>{name}</li>)
              ) : (
                <li>No elevated account risk today</li>
              )}
            </ul>
          </div>
        </div>

        <h4>Brief Markdown</h4>
        <pre>{brief.markdown}</pre>
      </article>
    </section>
  );
}
